const Images = {
  logo: require('../assets/Images/elephant.png'),
  menu: require('../assets/Images/menu.png'),
  responsive: require('../assets/Images/responsive.png'),
  scan: require('../assets/Images/scan.png'),
  value: require('../assets/Images/value.png'),
  noRecord: require('../assets/Images/noRecord.png'),
  mail: require('../assets/Images/mail.png'),
  lock: require('../assets/Images/lock.png'),
  down: require('../assets/Images/down.png'),
  calendar: require('../assets/Images/calendar.png'),
  gallery: require('../assets/Images/gallery.png'),
  camera: require('../assets/Images/camera.png'),
  search: require('../assets/Images/search.png'),
  user: require('../assets/Images/user.png'),
  splash: require('../assets/Images/splash.jpg'),
  delete: require('../assets/Images/delete.png'),
  contract: require('../assets/Images/contract.png'),
  depreciation: require('../assets/Images/depreciation.png'),
  folder: require('../assets/Images/folder.png'),
  logout: require('../assets/Images/logout.png'),
  lostItems: require('../assets/Images/lost-items.png'),
  settings: require('../assets/Images/settings.png'),
  star: require('../assets/Images/star.png'),
  upload: require('../assets/Images/upload-big-arrow.png'),
  write: require('../assets/Images/write.png'),
  list: require('../assets/Images/list.png'),
  filter: require('../assets/Images/filter.png'),
  scanner: require('../assets/Images/scanner.png'),
  barcode: require('../assets/Images/barcode.png'),
  hotspot: require('../assets/Images/hotspot.png'),
  bluetooth: require('../assets/Images/bluetooth.png'),
};

export default Images;
