export const AUTH_ACTION_TYPES = {
  LOGIN: 'LOGIN_ACTION',
  REGISTER: 'REGISTER_ACTION',
  AUTH_FAILED: 'AUTH_FAILED',
  RESET_AUTH_STATE: 'RESET_AUTH_STATE',
  LOGOUT: 'USER_LOGOUT',
  UPDATE: 'USER_UPDATE',
};

export const LOCATION_ACTION_TYPES = {
  CREATE: 'CREATE_LOCATION',
  DELETE: 'DELETE_LOCATION',
  UPDATE: 'UPDATE_LOCATION',
  GET: 'GET_LOCATION',
  GET_ALL: 'GET_ALL_LOCATIONS',
};

export const SITE_ACTION_TYPES = {
  CREATE: 'CREATE_SITE',
  DELETE: 'DELETE_SITE',
  UPDATE: 'UPDATE_SITE',
  GET: 'GET_SITE',
  GET_ALL: 'GET_ALL_SITES',
};

export const CATEGORY_ACTION_TYPES = {
  CREATE: 'CREATE_CATEGORY',
  DELETE: 'DELETE_CATEGORY',
  UPDATE: 'UPDATE_CATEGORY',
  GET: 'GET_CATEGORY',
  GET_ALL: 'GET_ALL_CATEGORIES',
};

export const ASSET_ACTION_TYPES = {
  CREATE: 'CREATE_ASSET',
  DELETE: 'DELETE_ASSET',
  UPDATE: 'UPDATE_ASSET',
  GET: 'GET_ASSET',
  GET_ALL: 'GET_ALL_ASSETS',
};

export const ASSET_FIELD_ACTION_TYPES = {
  CREATE: 'CREATE_ASSET_FIELD',
  DELETE: 'DELETE_ASSET_FIELD',
  UPDATE: 'UPDATE_ASSET_FIELD',
  GET: 'GET_ASSET_FIELD',
  GET_ALL: 'GET_ALL_ASSET_FIELDS',
};

export const EMPLOYEE_ACTION_TYPES = {
  CREATE: 'CREATE_EMPLOYEE',
  DELETE: 'DELETE_EMPLOYEE',
  UPDATE: 'UPDATE_EMPLOYEE',
  GET: 'GET_EMPLOYEE',
  GET_ALL: 'GET_ALL_EMPLOYEES',
};

export const MAINTENANCE_ACTION_TYPES = {
  CREATE: 'CREATE_MAINTENANCE',
  DELETE: 'DELETE_MAINTENANCE',
  UPDATE: 'UPDATE_MAINTENANCE',
  GET: 'GET_MAINTENANCE',
  GET_ALL: 'GET_ALL_MAINTENANCE',
};
